---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: demo-webserver
        image: lkurkela/demo-webserver:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "200M"
            cpu: "1"
          requests:
            memory: "100M"
            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: demo
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: webserver

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webserver
  namespace: demo
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  rules:
  - host: web.dev-managed-kube.srv.hosting.fi
    http:
      paths:
      - path: /
        backend:
          serviceName: webserver
          servicePort: 80
  tls:
  - hosts:
    - web.dev-managed-kube.srv.hosting.fi
    secretName: web-dev-managed-kube
